print('i Start')
print('  test.py for CircleCI')
from core.lib.emulator import *
print('i from core.lib.emulator import *')
end(file,source)
print('i end(file,source)')
print('i Success!')
print('i End')
print('i exit(0)')
exit(0)
